language: java

jdk:
  - oraclejdk8

sudo: false

install:
  - mvn  clean 

script:
  - mvn verify 

after_success:
  body='{
"request": {
"branch":"master"
}}'

curl -s -X POST \
   -H "Content-Type: application/json" \
   -H "Accept: application/json" \
   -H "Travis-API-Version: 3" \
   -H "Authorization: token ${TRAVIS_API_TOKEN}" \
   -d "$body" \
   https://api.travis-ci.org/repo/shrawannirala%2FtestInterCI/requests

cache:
  apt: true
  directories:

