language: java

jdk:
  - oraclejdk8

sudo: false

install:
  - mvn  clean 

script:
  - mvn verify 

after_success:
  - mvn coveralls:report --settings=settings.xml

cache:
  apt: true
  directories:

